apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:franciscoxaviersp/homelab-charts.git
    targetRevision: HEAD
    path: arr-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
        prune: true 
        selfHeal: true
        allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true