apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:franciscoxaviersp/homelab-charts.git
    targetRevision: HEAD
    path: jellyfin
    helm:
      values: |
        persistence:
          config:
            size: 5Gi
            accessModes:
            - ReadWriteOnce
          cache:
            size: 10Gi
            accessModes:
            - ReadWriteOnce
          media:
            size: 200Gi
            accessModes:
            - ReadWriteMany
            storageClass: "ceph-filesystem"
          fonts:
            size: 500Mi
            accessModes:
            - ReadWriteOnce
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    retry:
      limit: 2
    automated:
        prune: true 
        selfHeal: true
        allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true