apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  project: default
  source:
    chart: coredns
    repoURL: https://coredns.github.io/helm
    targetRevision: 1.45.0
    helm:
      values: |
        isClusterService: false
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true