apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 3.2.0
    chart: eck-operator-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /metadata/labels/app.kubernetes.io~1instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
