apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-local
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.19.0
    helm:
      values: |
        provider:
          name: pihole
        domainFilters:
          - "local.be-an-explorer.com"
        sources:
          - crd
        registry: noop
        policy: upsert-only
        extraArgs:
          - --pihole-server=http://pihole-web.infra.svc.cluster.local  # Update with your Pi-hole service URL
          - --pihole-api-version=6  # Use 6 for Pi-hole v6, 5 for older
        env:
          - name: EXTERNAL_DNS_PIHOLE_PASSWORD
            value: "your-pihole-password"  # Replace with your Pi-hole web password
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true