apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: 10.2.0
    chart: goldilocks
    helm:
      values: |
        controller:
          flags:
            on-by-default: true
        dashboard:
          flags:
            on-by-default: true
          replicaCount: 1
          resources:
            limits: {}
            requests:
              cpu: 25m
              memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true