apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://haproxytech.github.io/helm-charts
    targetRevision: 1.45.0
    chart: kubernetes-ingress
    helm:
      values: |
        controller:
          replicaCount: 1
          service:
            type: LoadBalancer
            # MetalLB will assign an external IP automatically
            loadBalancerIP: ""
          ingressClass: haproxy
          gatewayAPI:
            enabled: true

        # RBAC and namespace settings
        rbac:
          create: true

        metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true