apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:franciscoxaviersp/argocd-apps.git
    path: infrastructure/homelab/manifests/keycloak-crds
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true