apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
spec: #
  project: default
  source:
    repoURL: https://cowboysysop.github.io/charts
    targetRevision: 11.1.0
    chart: vertical-pod-autoscaler
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true