name: Apply Changed App of Apps on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  apply-app-of-apps:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect changed clusters
        id: detect
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          echo "Changed files:"
          echo "$CHANGED_FILES"
          CLUSTERS=""
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" == clusters/*/*.yaml ]]; then
              CLUSTER_NAME=$(echo "$FILE" | cut -d'/' -f2)
              CLUSTERS="$CLUSTERS $CLUSTER_NAME"
            fi
          done
          echo "clusters=$CLUSTERS" >> $GITHUB_OUTPUT

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Apply to changed clusters
        if: steps.detect.outputs.files != ''
        run: |
          declare -A CLUSTER_APPS

          # Group files by cluster
          for FILE in ${{ steps.detect.outputs.files }}; do
            CLUSTER=$(echo "$FILE" | cut -d'/' -f2)
            CLUSTER_APPS[$CLUSTER]="${CLUSTER_APPS[$CLUSTER]} $FILE"
          done

          for CLUSTER in "${!CLUSTER_APPS[@]}"; do
            echo "Applying all App of Apps for cluster: $CLUSTER"
            mkdir -p $HOME/.kube
            echo "${{ secrets[KUBECONFIG_${CLUSTER^^}] }}" > $HOME/.kube/config
            chmod 600 $HOME/.kube/config
            
            for FILE in ${CLUSTER_APPS[$CLUSTER]}; do
              echo "Applying $FILE..."
              kubectl apply -f $FILE
            done
          done