name: Deploy to Cluster

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Cluster name to deploy to'
        required: true
      base_sha:
        description: 'Base sha'
        required: false
      merge_commit_sha:
        description: 'Merge commit sha'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate diff manually
        env:
          CLUSTER: ${{ github.event.inputs.cluster }}
          BASE_SHA: ${{ github.event.inputs.base_sha }}
          MERGE_SHA: ${{ github.event.inputs.merge_commit_sha }}
        run: |
          git fetch origin $BASE_SHA
          git fetch origin $MERGE_SHA
          git diff --name-only $BASE_SHA $MERGE_SHA \
            | grep "^clusters/${CLUSTER}/.*\.yaml$" > diff.txt || true
          echo "Diffed files:"
          cat diff.txt

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Install OpenVPN client
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Prepare VPN config & certs
        env:
          CLUSTER: ${{ github.event.inputs.cluster }}
        run: |
          mkdir -p vpn
          case "$CLUSTER" in
            homelab)
              echo "${{ secrets.OPENVPN_CONF_HOMELAB }}" > vpn/client.ovpn
              echo "${{ secrets.OPENVPN_CA_HOMELAB }}" > vpn/ca.crt
              echo "${{ secrets.OPENVPN_CERT_HOMELAB }}" > vpn/client.crt
              echo "${{ secrets.OPENVPN_KEY_HOMELAB }}" > vpn/client.key
              echo "${{ secrets.OPENVPN_TLS_HOMELAB }}" > vpn/tls.key
              echo "${{ secrets.OPENVPN_CREDENTIALS_HOMELAB }}" > vpn/credentials.txt
              ;;
            *)
              echo "Unknown cluster $CLUSTER"
              exit 1
              ;;
          esac

      - name: Setup kubeconfig
        env:
          CLUSTER: ${{ github.event.inputs.cluster }}
        run: |
          mkdir -p $HOME/.kube
          case "$CLUSTER" in
            homelab)
              echo "${{ secrets.KUBECONFIG_HOMELAB }}" > $HOME/.kube/config
              ;;
            *)
              echo "Unknown cluster $CLUSTER"
              exit 1
              ;;
          esac
          chmod 600 $HOME/.kube/config

      - name: Connect VPN
        run: |
          sudo openvpn --config ./vpn/client.ovpn --daemon
          sleep 15
          echo "VPN connected successfully."

      - name: Loop over diff and apply changes
        env:
          BASE_BRANCH: ${{ github.event.inputs.base_sha }}
          CLUSTER: ${{ github.event.inputs.cluster }}
        run: |
          if [ -z "$BASE_BRANCH" ]; then
            echo "No base_branch provided. Applying all files in ./clusters/$CLUSTER/"
            for path in ./clusters/$CLUSTER/*.yaml; do
              kubectl apply -f $path
            done
          else
            echo "Applying only diffed files from $BASE_BRANCH..."
            while IFS= read -r file; do
              echo "Processing $file"
              # Run your command here, for example:
              kubectl apply -f "$file"
            done < diff.txt
          fi