name: Deploy to Cluster

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Cluster name to deploy to'
        required: true
      base_branch:
        description: 'Base branch for the deployment'
        required: true
      head_ref:
        description: 'Head ref for the deployment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.head_ref }}
      - name: Fetch base branch
        run: git fetch origin ${{ github.event.inputs.base_branch }}:${{ github.event.inputs.base_branch }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Install OpenVPN client
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Prepare VPN config & certs
        env:
          CLUSTER: ${{ github.event.inputs.cluster }}
        run: |
          mkdir -p vpn
          case "$CLUSTER" in
            homelab)
              echo "${{ secrets.OPENVPN_CONF_HOMELAB }}" > vpn/client.ovpn
              echo "${{ secrets.OPENVPN_CA_HOMELAB }}" > vpn/ca.crt
              echo "${{ secrets.OPENVPN_CERT_HOMELAB }}" > vpn/client.crt
              echo "${{ secrets.OPENVPN_KEY_HOMELAB }}" > vpn/client.key
              echo "${{ secrets.OPENVPN_TLS_HOMELAB }}" > vpn/tls.key
              echo "${{ secrets.OPENVPN_CREDENTIALS_HOMELAB }}" > vpn/credentials.txt
              ;;
            *)
              echo "Unknown cluster $CLUSTER"
              exit 1
              ;;
          esac
          cat vpn/client.ovpn
      
      - uses: GrantBirki/git-diff-action@v2.8.1
        id: git-diff-action
        with:
          base_branch: ${{ github.event.inputs.base_branch }}
          json_diff_file_output: diff.json
          file_output_only: "true"
          search_path: ./clusters/${CLUSTER}/*.yaml
      - name: print json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: cat $DIFF

      - name: Setup kubeconfig
        env:
          CLUSTER: ${{ github.event.inputs.cluster }}
        run: |
          mkdir -p $HOME/.kube
          case "$CLUSTER" in
            homelab)
              echo "${{ secrets.KUBECONFIG_HOMELAB }}" > $HOME/.kube/config
              ;;
            *)
              echo "Unknown cluster $CLUSTER"
              exit 1
              ;;
          esac
          chmod 600 $HOME/.kube/config

      - name: Connect VPN
        run: |
          sudo openvpn --config ./vpn/client.ovpn --daemon
          sleep 15
          echo "VPN connected successfully."

      - name: Loop over diff and apply changes
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: |
          for path in $(jq -r '.files[].path' $DIFF); do
            echo "Running command for $path"
            # Example: run kubectl apply
            echo "kubectl apply -f $path"
          done